apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: k8s-worker1
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: http
