apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cj
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ubuntu
              image: ubuntu:22.04
              args:
                - /bin/sh
                - -c
                - date; echo Hello from cron sample
          restartPolicy: OnFailure
