apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: writer-container
          image: alpine
          command: ["/bin/sh"]
          args:
            ["-c", "while true; do date >> /var/logs/index.html;sleep 10;done"]
          volumeMounts:
            - name: shared-volume
              mountPath: /var/logs
        - name: serving-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shared-volume
          emptyDir: {}
