apiVersion: apps/v1
kind: Deployment
metadata:
  name: down-api-deploy
  labels:
    app: down-api
spec:
  selector:
    matchLabels:
      app: down-api
  template:
    metadata:
      labels:
        app: down-api
    spec:
      containers:
        - name: write-container
          image: alpine
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do echo MEM:$MEM_LIMIT CPU:$CPU_LIMIT $(date):$POD_IP:$POD_NAME:$(cat /var/logs/index.html) > /proc/1/fd/1; sleep 10; done",
            ]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: write-container
                  resource: limits.memory
                  divisor: 1Mi
            - name: CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: write-container
                  resource: limits.cpu
                  divisor: 1m
          volumeMounts:
            - name: shared-data
              mountPath: /var/logs
          resources:
            limits:
              memory: "200Mi"
              cpu: "250m"
            requests:
              memory: "150Mi"
              cpu: "200m"
      volumes:
        - name: shared-data
          downwardAPI:
            items:
              - path: index.html
                fieldRef:
                  fieldPath: metadata.name
