apiVersion: v1
kind: Pod
metadata:
  name: poda-demo
  labels:
    app: nginx-src
  namespace: source
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
