apiVersion: v1
kind: Pod
metadata:
  name: podc-demo
  labels:
    app: nginx
  namespace: monitoring
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
