apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - "ls"
        - "-l"
        - "/var/tmp"
      volumeMounts:
        - name: db-files
          mountPath: /var/tmp
  volumes:
    - name: db-files
      secret:
        secretName: dbsecrets
