apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app: cicd
  ports:
    - name: cicd-port
      port: 80
      targetPort: 8080
      nodePort: 32002
      protocol: TCP