apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: '0.5m'
          memory: '128Mi'
        limits:
          cpu: '1m'
          memory: '265Mi'
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: env
                operator: In
                values: 
                  - dev
                  - prod