apiVersion: v1
kind: ConfigMap
metadata:
  name: db-backup-script
data:
  db_backup.sh: |
    #!/bin/bash
    echo "backup was initialized"
    mysqldump -hmysql-svc.default -uroot -psupersecret --all-databases > /var/tmp/db_backup.sql
    echo "backup task was successful"
