apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "125m"
          memory: "256Mi"
        requests:
          cpu: "125m"
          memory: "256Mi"
      volumeMount:
        - name: shared-volume
          mountPath: /var/www/html
  volumes:
    - name: shared-volume
      emptyDir: {}
