apiVersion: v1
kind: Pod
metadata:
  name: nginx01
  labels:
    app: nginx01
    type: webapp
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: env
                operator: In
                values:
                - dev
                - prod
  containers:
    - name: writer-container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c","while true;do date >> /var/logs/index.html;sleep 10;done"]
      volumeMounts:
        - name: nginx-data
          mountPath: /var/logs
      resources:
        requests:
          cpu: '0.5m'
          memory: '128Mi'
        limits:
          cpu: '1m'
          memory: '256Mi'
    - name: serving-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: '0.5m'
          memory: '128Mi'
        limits:
          cpu: '1m'
          memory: '256Mi'
      volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-data
      emptyDir: {}