apiVersion: v1
kind: Pod
metadata:
  name: nginx02
  labels: 
    app: nginx02
    type: webapp
spec: 
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: type
                operator: In
                values: 
                  - webapp
          topologyKey: kubernetes.io/hostname
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: '0.5m'
          memory: '128Mi'
        limits:
          cpu: '1m'
          memory: '256Mi'
