apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-net-policy
  namespace: destination
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: nginx
        - namespaceSelector:
            matchLabels:
              env: prod
      ports:
        - port: 80
          protocol: TCP
