apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-hostpath
  labels:
    type: hostpath
    environment: dev
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/tmp"
