apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  tolerations:
    - key: type
      operator: Equal
      value: master
      effect: NoSchedule
    
    - key:  "node-role.kubernetes.io/control-plane"
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: type
              operator: "In"
              values:
                - master
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "0.5m"
          memory: "128Mi"
        limits:
          cpu: "1m"
          memory: "256Mi"
