apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    app: nginx
spec:
  containers:
    - name: writer-container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true;do date >> /var/logs/index.html;sleep 10;done"]
      volumeMounts:
        - name: shared-data
          mountPath: /var/logs
        - name: user-info
          mountPath: /var/user-data/user_info.php
    - name: nginx-server
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-data
      hostPath:
        path: /var/user-data
        type: DirectoryOrCreate

    - name: user-info
      hostPath:
        path: /var/user-data/user_info.php
        type: FileOrCreate
