apiVersion: v1
kind: Pod
metadata:
  name: podb-demo
  labels:
    app: nginx-dst
  namespace: destination
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
