apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app: jenkins
    environment: dev
  ports:
    - name: jenkins-port
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32002
