apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: jenkins
    environment: dev
spec:
  storageClassName: nfs
  accessModes:
    # we are going to run only one replica for jenkins so
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.105.17
    path: /var/nfs/jenkins-data
