apiVersion: v1
kind: Service
metadata:
  name: nodeexporter-service
  namespace: monitoring
  labels:
    k8s-app: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9100'
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    k8s-app: node-exporter
