apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-role-binding
  namespace: default
subjects:
  - kind: User
    name: kode
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-read-access
  apiGroup: rbac.authorization.k8s.io
