apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    app: nginx
spec:
  containers:
    - name: writer-container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true;do date >> /var/logs/index.html;sleep 10;done"]
      volumeMounts:
        - name: shared-data
          mountPath: /var/logs

    - name: nginx-server
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-data
      hostPath:
        path: /tmp/data
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: hostpath-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      nodePort: 32001
