apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-02-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-02
      type: webapp
  template:
    metadata:
      labels:
        app: nginx-02
        type: webapp
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: type
                      operator: In
                      values:
                        - webapp
            
      containers:
      - name: nginx-deployment
        image: nginx
        resources:
          requests:
            memory: "108Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
