apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
      type: webapp
  template:
    metadata:
      labels:
        app: nginx
        type: webapp
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: env
                    operator: In
                    values:
                     - prod
              weight: 10
      containers:
      - name: nginx-deployment
        image: nginx
        resources:
          requests:
            memory: "108Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
