apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
spec:
  containers:
    - name: writer-container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/logs/index.html;sleep 10;done"]
      volumeMounts:
        - name: shared-volumes
          mountPath: /var/logs
    - name: nginx-server
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-volumes
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-volumes
      # emptyDir: {}
      emptyDir:
        medium: Memory
        sizeLimit: 300Mi
